name: IMDB ETL

on:
  workflow_dispatch:
  schedule:
    - cron: "15 5 * * *"

jobs:
  etl:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run ETL
        run: python etl.py

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -Iseconds)
          git commit -m "Ran ETL at ${timestamp}" || exit 0
          git push
